version: "3"

services:
  tg_downloader:
    image: tg_downloader:latest
    container_name: tg
    volumes:
    - ./src1/:/srv/
    - /root/tg_downloads/:/srv/downloads
    command: ["python", "main.py"]
    env_file:
    - .env